version: '2'
services:
  dashboard:
    image: dashboard
    command: [./wait-for-it.sh, "redis:6379", "--",  "/dashboard"]
    build:
      context: "./dashboard"
      dockerfile: Dockerfile   
    ports:
      - 8080:8080
    depends_on:
      - redis
      - heat-sensor-service
      - humidity-sensor-service
      - pressure-sensor-service
    links:
      - redis
      - elasticsearch
  heat-sensor-service:
    image: heat-sensor-service
    command: [./wait-for-it.sh, "elasticsearch:9200", "--",  "/heat-sensor-service"]
    build:
      context: "./services/heat"
      dockerfile: Dockerfile   
    ports:
      - 3000:3000
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch
  humidity-sensor-service:
    image: humidity-sensor-service
    command: [./wait-for-it.sh, "elasticsearch:9200", "--",  "/humidity-sensor-service"]
    build:
      context: "./services/humidity"
      dockerfile: Dockerfile   
    ports:
      - 3001:3001
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch
  pressure-sensor-service:
    image: pressure-sensor-service
    command: [./wait-for-it.sh, "elasticsearch:9200", "--",  "/pressure-sensor-service"]
    build:
      context: "./services/pressure"
      dockerfile: Dockerfile   
    ports:
      - 3002:3002
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.14
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type=single-node
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  es_data:
    driver: local