version: '2'
services:
  heat-sensor-service:
    image: heat-sensor-service
    command: [./wait-for-it.sh, "elasticsearch:9200", "--",  "/heat-sensor-service"]
    build:
      context: "./heat-sensor-service"
      dockerfile: Dockerfile   
    ports:
      - 3000:3000
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch
  humidity-sensor-service:
    image: humidity-sensor-service
    command: [./wait-for-it.sh, "elasticsearch:9200", "--",  "/humidity-sensor-service"]
    build:
      context: "./humidity-sensor-service"
      dockerfile: Dockerfile   
    ports:
      - 3001:3001
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch
  pressure-sensor-service:
    image: pressure-sensor-service
    command: [./wait-for-it.sh, "elasticsearch:9200", "--",  "/pressure-sensor-service"]
    build:
      context: "./pressure-sensor-service"
      dockerfile: Dockerfile   
    ports:
      - 3002:3002
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.14
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type=single-node
  redis:
    #image: eliar/redis
    image: redis
    ports:
      - "6379:6379"

volumes:
  es_data:
    driver: local